authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket_view, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('remove/', basketapp.basket_remove_all, name='remove_all'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

bookshop/urls.py
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('shares/', mainapp.shares, name='shares'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.catalog, name='index'),
    path('category/<int:pk>/', mainapp.catalog, name='category'),
    path('book/<int:pk>/', mainapp.book_page, name='book'),
    path('category/<int:pk>/page/<int:page>/', mainapp.catalog, name='page')
]

mainapp/models.py
from django.db import models


class BookCategory(models.Model):
    name = models.CharField(verbose_name='категория', max_length=32)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return '{}'.format(self.name)


class Book(models.Model):
    category = models.ForeignKey(BookCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='название', max_length=64, unique=True)
    address = models.CharField(verbose_name='адрес', max_length=32)
    author = models.CharField(verbose_name='автор', max_length=32, blank=True)
    publishing = models.CharField(verbose_name='издательство', max_length=32, blank=True)
    papers = models.CharField(verbose_name='количество и тип страниц', max_length=32, blank=True)
    mass = models.IntegerField(verbose_name='масса', default=0)
    size = models.CharField(verbose_name='размер', max_length=32, blank=True)
    disc = models.TextField(verbose_name='кратко', blank=True)
    extra_disc = models.TextField(verbose_name='подробно', blank=True)
    price = models.IntegerField(verbose_name='цена', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)

mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, get_object_or_404
from .models import Book, BookCategory
from basketapp.models import Basket
from authapp.forms import ShopUserContactForm
from django.urls import reverse
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
from logger.logger_config import log


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_bestseller():
    books = Book.objects.filter(is_active=True, category__is_active=True)

    return random.sample(list(books), 1)[0]


def get_same_books(bestseller):
    same_books = Book.objects.filter(category=bestseller.category, is_active=True, category__is_active=True).exclude(pk=bestseller.pk)[:4]

    return same_books


@log('Main page is active')
def main(request):
    bestseller = get_bestseller()
    same_books = get_same_books(bestseller)
    new_books = Book.objects.filter(is_active=True, category__is_active=True)[14:20]
    basket = get_basket(user=request.user)
    content = {'basket': basket, 'new_books': new_books, 'bestseller': bestseller, 'same_books': same_books}
    return render(request, 'mainapp/index.html', content)


@log('Basket is active')
@login_required
def basket_view(request):
    basket = get_basket(user=request.user)
    basket_items = basket.order_by('book__category')
    content = {'basket': basket, 'basket_items': basket_items}
    return render(request, 'mainapp/basket.html', content)


@log('Catalog is active')
def catalog(request, pk=None, page=1):
    print(pk)
    links_menu = BookCategory.objects.filter(is_active=True)
    book_list = Book.objects.filter(is_active=True, category__is_active=True)
    new_books = Book.objects.filter(is_active=True, category__is_active=True)[14:20]

    paginator = Paginator(book_list, 10)
    try:
        books_paginator = paginator.page(page)
    except PageNotAnInteger:
        books_paginator = paginator.page(1)
    except EmptyPage:
        books_paginator = paginator.page(paginator.num_pages)

    basket = get_basket(user=request.user)

    if pk:
        if pk == '0':
            category = {'name': 'Все жанры'}
            book_list = Book.objects.filter(is_active=True, category__is_active=True)
        else:
            category = get_object_or_404(BookCategory, pk=pk, is_active=True)
            category_len = Book.objects.filter(category=category)
            book_list = Book.objects.filter(category__pk=pk, is_active=True, category__is_active=True)
        paginator = Paginator(book_list, 10)
        try:
            books_paginator = paginator.page(page)
        except PageNotAnInteger:
            books_paginator = paginator.page(1)
        except EmptyPage:
            books_paginator = paginator.page(paginator.num_pages)
        content = {
            'links_menu': links_menu,
            'book_list': books_paginator,
            'category': category,
            'category_len': category_len,
            'basket': basket,
            'new_books': new_books,
        }
        return render(request, 'mainapp/catalog.html', content)

    content = {
        'links_menu': links_menu,
        'book_list': books_paginator,
        'basket': basket,
        'new_books': new_books,
    }
    return render(request, 'mainapp/catalog.html', content)


@log('Book page is active')
def book_page(request, pk):
    book = get_object_or_404(Book, pk=pk, is_active=True, category__is_active=True)
    same_books = Book.objects.filter(category__pk=book.category.pk, is_active=True, category__is_active=True).exclude(pk=book.pk)[:6]

    basket = get_basket(user=request.user)

    content = {
        'links_menu': BookCategory.objects.all(),
        'book': book,
        'same_books': same_books,
        'basket': basket
    }

    return render(request, 'mainapp/book.html', content)


@log('Contact page is active')
def contact(request):
    basket = get_basket(user=request.user)

    if request.method == 'POST':
        contact_form = ShopUserContactForm(request.POST)
        username = request.POST['username']
        email = request.POST['email']
        theme = request.POST['theme']
        data = request.POST['data']
        if username and email and theme and data:
            try:
                send_mail('{} : {}'.format(username, theme), data, email, ['toscha.nv@gmail.com'], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect(reverse('contact'))
    else:
        contact_form = ShopUserContactForm()
    content = {'contact_form': contact_form, 'basket': basket}
    return render(request, 'mainapp/contact.html', content)


@log('Shares page is active')
def shares(request):
    bestseller1 = get_bestseller()
    bestseller2 = get_bestseller()
    same_books1 = get_same_books(bestseller1)
    same_books2 = get_same_books(bestseller2)
    basket = get_basket(user=request.user)
    content = {
        'basket': basket,
        'bestseller1': bestseller1,
        'bestseller2': bestseller2,
        'same_books1': same_books1,
        'same_books2': same_books2
    }
    return render(request, 'mainapp/shares.html', content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<div>
    <ul class="sub-menu">

        <a href="{% url 'catalog:category' 0 %}" class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">
            <li>Все жанры {% if request.resolver_match.kwargs.pk == 0 %}({{book_list|length}}){% endif %}</li>
        </a>

        {% for link in links_menu %}
        <a href="{% url 'catalog:category' link.pk %}" class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}active{% endif %}">
            <li>{{link.name}} {% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}({{category_len|length}}){% endif %}</li>
        </a>
        {% endfor %}

    </ul>
    
    <p></p>
    
    <ul class="sub-menu">
      
        <a href="#" class="filter">
            <li>Цена: убывание</li>
        </a>
       
        <a href="#" class="filter">
            <li>Цена: возрастание</li>
        </a>

    </ul>
</div>

mainapp/templates/mainapp/includes/inc_footer_menu.html
<ul class="footer-menu">

    <a href="{% url 'main' %}">
        <li>Главная</li>
    </a>
    <li>|</li>
    <a href="{% url 'catalog:category' 0 %}">
        <li>Каталог</li>
    </a>
    <li>|</li>
    <a href="{% url 'shares' %}">
        <li>Акции</li>
    </a>
    <li>|</li>
    <a href="{% url 'basket:view' %}">
        <li>Корзина</li>
    </a>
    <li>|</li>
    <a href="{% url 'contact' %}">
        <li>Контакты</li>
    </a>

</ul>

mainapp/templates/mainapp/includes/inc_main_menu.html
<nav>
   
    <ul class="main-menu">
       
        <a href ="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">
        <li>Главная</li>
        </a>
        
        <a href ="{% url 'catalog:category' 0 %}" class="{% if request.resolver_match.namespace == 'catalog' %}active{% endif %}">
        <li>Каталог</li>
        </a>
        
        <a href ="{% url 'shares' %}" class="{% if request.resolver_match.url_name == 'shares' %}active{% endif %}">
        <li>Акции</li>
        </a>
        
        <a href ="{% url 'basket:view' %}" class="{% if request.resolver_match.namespace == 'basket' %}active{% endif %} basket-view">
            <li>Корзина{% if basket %}
            <p class="basket-counter">{{basket.0.total_quantity}}</p>
            <p class="basket-info">{{basket.0.total_quantity}} товаров на сумму {{basket.0.total_cost}} руб.</p>
            {% endif %}</li>
        </a>
        
        <a href ="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
        <li>Контакты</li>
        </a>

    </ul>

</nav>

mainapp/templates/mainapp/includes/inc_related_book.html
{% load staticfiles %}
<div class="book">

    <img src="{% static book.address %}" width="92.5" height="136">
    <a class="book-link" href="{% url 'catalog:book' book.pk %}">{{book.name}}</a>
    <p class="price">{{book.price}} р.</p>
    <a class="buy-link" href="{% url 'basket:add' book.pk %}">В корзину</a>

</div>