authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

bookshop/urls.py
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('shares/', mainapp.shares, name='shares'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    name = models.CharField(verbose_name='никнейм', max_length=32)
    is_active = models.BooleanField(verbose_name='активна', default=True)

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegistrationForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class ShopUserContactForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    theme = forms.CharField(max_length=100)
    data = forms.CharField(widget=forms.Textarea)

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserRegistrationForm, ShopUserEditForm
from django.contrib import auth
from django.urls import reverse
from basketapp.models import Basket
from logger.logger_config import log


@log('Log in page is active')
def login(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    next = request.GET['next'] if 'next' in request.GET.keys() else ''
    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))
    else:
        login_form = ShopUserLoginForm()
    content = {
        'login_form': login_form,
        'basket': basket,
        'next': next
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


@log('Registration page is active')
def register(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    if request.method == 'POST':
        register_form = ShopUserRegistrationForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegistrationForm()
    content = {'register_form': register_form, 'basket': basket}
    return render(request, 'authapp/register.html', content)


@log('Editing page is active')
def edit(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
    content = {'edit_form': edit_form, 'basket': basket}
    return render(request, 'authapp/edit.html', content)

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}
{% block title %}
<title>Редактирование</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}
<div class="enter">
    <h3 class='edit-h'>Редактирование:</h3>
    <form action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <input type="reset" value="Отменить">
        <input type="submit" value="Сохранить">
    </form>
</div>
<div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}
{% block title %}
<title>Вход</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}
<div class="enter">
    <h3>Вход:</h3>
    <form action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {% if next %}
        <input type="hidden" name="next" value="{{next}}">
        {% endif %}
        {{ login_form.as_p }}
        <a href="{% url 'auth:register' %}">Зарегистрироваться</a>
        <br>
        <input type="reset" value="Очистить">
        <input type="submit" value="Войти">
    </form>
</div>
{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/user.css' %}">
{% endblock %}
{% block title %}
<title>Регистрация</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}
<div class="enter">
    <h3>Регистрация:</h3>
    <form action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <input type="reset" value="Очистить">
        <input type="submit" value="Зарегистрироваться">
    </form>
</div>
{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}