adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('books/read/category/<int:pk>/', adminapp.books, name='books'),
    path('books/create/category/<int:pk>/', adminapp.book_create, name='book_create'),
    path('books/read/<int:pk>/', adminapp.BookDetailView.as_view(), name='book_read'),
    path('books/update/<int:pk>/', adminapp.book_update, name='book_update'),
    path('books/delete/<int:pk>/', adminapp.book_delete, name='book_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

bookshop/urls.py
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('shares/', mainapp.shares, name='shares'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import BookCategory, Book


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class BookCategoryEditForm(forms.ModelForm):
    class Meta:
        model = BookCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(BookCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class BookEditForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(BookEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from authapp.models import ShopUser
from mainapp.models import BookCategory, Book
from authapp.forms import ShopUserRegistrationForm
from adminapp.forms import ShopUserAdminEditForm, BookCategoryEditForm, BookEditForm
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils.decorators import method_decorator


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super(UserListView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        return context


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin:users')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание пользователя'
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin:users')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование'
        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Удаление'
        return context


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'Категории'
    categories_list = BookCategory.objects.all()

    content = {
        'title': title,
        'objects': categories_list,
    }

    return render(request, 'adminapp/categories.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'Создание категории'

    if request.method == 'POST':
        category_form = BookCategoryEditForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
    else:
        category_form = BookCategoryEditForm()

    content = {
        'title': title,
        'form': category_form,
    }

    return render(request, 'adminapp/category_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_update(request, pk):
    title = 'Редактирование'
    edit_category = get_object_or_404(BookCategory, pk=pk)

    if request.method == 'POST':
        edit_form = BookCategoryEditForm(request.POST, request.FILES, instance=edit_category)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:category_update', args=[edit_category.pk]))
    else:
        edit_form = BookCategoryEditForm(instance=edit_category)

    content = {
        'title': title,
        'form': edit_form,
    }

    return render(request, 'adminapp/category_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk):
    title = 'Удаление'
    category = get_object_or_404(BookCategory, pk=pk)

    if request.method == 'POST':
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse('admin:categories'))

    content = {
        'title': title,
        'category_to_delete': category,
    }

    return render(request, 'adminapp/category_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def books(request, pk):
    title = 'Книги'
    category = get_object_or_404(BookCategory, pk=pk)
    books_list = Book.objects.filter(category=category)

    content = {
        'title': title,
        'category': category,
        'objects': books_list,
    }

    return render(request, 'adminapp/books.html', content)


class BookDetailView(DetailView):
    model = Book
    template_name = 'adminapp/book_read.html'

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Просмотр'
        return context


@user_passes_test(lambda u: u.is_superuser)
def book_create(request, pk):
    title = 'Создание книги'
    category = get_object_or_404(BookCategory, pk=pk)

    if request.method == 'POST':
        book_form = BookEditForm(request.POST, request.FILES)
        if book_form.is_valid():
            book_form.save()
    else:
        book_form = BookEditForm(initial={'category': category})

    content = {
        'title': title,
        'form': book_form,
        'category': category,
    }

    return render(request, 'adminapp/book_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def book_update(request, pk):
    title = 'Редактирование'
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        edit_form = BookEditForm(request.POST, request.FILES, instance=book)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:book_update', args=[book.category.pk]))
    else:
        edit_form = BookEditForm(instance=book)

    content = {
        'title': title,
        'form': edit_form,
        'category': book.category,
    }

    return render(request, 'adminapp/book_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def book_delete(request, pk):
    title = 'Удаление'
    book = get_object_or_404(Book, pk=pk)
    category = book.category

    if request.method == 'POST':
        book.is_active = False
        book.save()
        return HttpResponseRedirect(reverse('admin:books', args=[category.pk]))

    content = {
        'title': title,
        'book_to_delete': book,
        'category': category,
    }

    return render(request, 'adminapp/book_delete.html', content)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="admin_container">
        {% block menu %}
            {% include 'adminapp/includes/inc_menu.html' %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

adminapp/templates/adminapp/book_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block content %}
<div class ="book_delete"  style="margin-left: 10px">
Уверены, что хотите удалить "{{ book_to_delete.name }}"?
<form action ="{% url 'admin:book_delete' book_to_delete.pk %}"
method="post">
{% csrf_token %}
<input class="btn btn-danger" type="submit" value="Удалить">
<a class="btn btn-success" href="{% url 'admin:books' category.pk %}">
Отмена
</a>
</form>
</div>
{% endblock %}

adminapp/templates/adminapp/book_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="books_list">
        <div class="card" style="margin: 20px">
            <img src="{% static object.address %}" alt="{{ object.name }}" width="92.5" height="136">
            <p class="book_name" style="white-space: wrap">
                {{ object.name|title }}
            </p>
            <div class="summary">
                <b>Цена: {{ object.price }} руб</b>
            </div>
            <div class="book_desc">
                {{ object.disc }}
            </div>
            <div class="book_extra_disc">
                {{ object.extra_disc }}
            </div>
            <div class="book_actions">
                <a class="btn btn-primary" href="{% url 'admin:book_read' object.pk %}" style="margin: 0 0 5px 5px">
                    Подробнее
                </a>
                <a class="btn btn-primary" href="{% url 'admin:book_delete' object.pk %}" style="margin: 0 0 5px 5px">
                    Удалить
                </a>
            </div>
            {% if object.is_active == False %}
                <p style="color: red">Не активна</p>
            {% endif %}
            <a class="btn btn-success" href ="{% url 'admin:books' category.pk %}">
            К списку книг
            </a>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/book_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class ="book_update"  style="margin-left: 10px">
<form action="" class ="form-horizontal" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input class ="form-control" type="submit" value="Сохранить">
</form>
<button class="btn btn-round form-control last">
<a class="btn btn-success" href ="{% url 'admin:books' category.pk %}">
К списку книг
</a>
</button>
</div>
{% endblock %}

adminapp/templates/adminapp/books.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="books_list">
    <a class="btn btn-primary" href="{% url 'admin:book_create' category.pk %}" style="margin: 20px">
        Новый продукт
    </a>
        {% for object in objects %}
            <div class="card" style="margin: 20px">
                <img src="{% static object.address %}" alt="{{ object.name }}" width="92.5" height="136">
                <p class="book_name" style="white-space: wrap">
                    {{ object.name|title }}
                </p>
                <div class="summary">
                    <b>Цена: {{ object.price }} руб</b>
                </div>
                <div class="book_desc">
                    {{ object.disc }}
                </div>
                <div class="book_actions">
                <a class="btn btn-primary" href="{% url 'admin:book_read' object.pk %}" style="margin: 0 0 5px 5px">
                    Подробнее
                </a>
                <a class="btn btn-primary" href="{% url 'admin:book_update' object.pk %}" style="margin: 0 0 5px 5px">
                    Редактировать
                </a>
                <a class="btn btn-primary" href="{% url 'admin:book_delete' object.pk %}" style="margin: 0 0 5px 5px">
                    Удалить
                </a>
                </div>
                {% if object.is_active == False %}
                    <p style="color: red">Не активна</p>
                {% endif %}
            </div>
        {% endfor%}
    </div>
{% endblock %}

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class="categories_list">
    <a class="btn btn-primary" href="{% url 'admin:category_create' %}" style="margin: 20px">
        Новая категория
    </a>
    {% for object in objects %}
        <div class="category_record" style="margin: 20px">
            <div class="category_name h5">
                {{ object.name|title }}
            </div>
            <div class="category_actions">
            <a class="btn btn-primary" href="{% url 'admin:books' object.pk %}">
                Книги категории
            </a>
            <a class="btn btn-primary" href="{% url 'admin:category_update' object.pk %}">
                Редактировать
            </a>
            <a class="btn btn-primary" href="{% url 'admin:category_delete' object.pk %}">
                Удалить
            </a>
            </div>
            <div class="category_desc">
                {{ object.description|title }}
            </div>
        </div>
    {% endfor%}
</div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block content %}
<div class ="category_delete"  style="margin-left: 10px">
Уверены, что хотите удалить "{{ category_to_delete.name }}"?
<form action ="{% url 'admin:category_delete' category_to_delete.pk %}"
method="post">
{% csrf_token %}
<input class="btn btn-danger" type="submit" value="Удалить">
<a class="btn btn-success" href="{% url 'admin:categories' %}">
Отмена
</a>
</form>
</div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class ="category_update"  style="margin-left: 10px">
<form action="" class ="form-horizontal" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input class ="form-control" type="submit" value="Сохранить">
</form>
<button class="btn btn-round form-control last">
<a class="btn btn-success" href ="{% url 'admin:categories' %}">
К списку категорий
</a>
</button>
</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block content %}
<div class ="user_delete"  style="margin-left: 10px">
Уверены, что хотите удалить {{ object.username }}
{% if object.first_name %}
({{ object.first_name|title }}
{% if object.last_name %}
{{ object.last_name|title }}{% endif %}){% endif %}?
<form action ="{% url 'admin:user_delete' object.pk %}"
method="post">
{% csrf_token %}
<input class="btn btn-danger" type="submit" value="Удалить">
<a class="btn btn-success" href="{% url 'admin:users' %}">
Отмена
</a>
</form>
</div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}
{% block title %}{{title}}{% endblock %}
{% block content %}
<div class ="user_update"  style="margin-left: 10px">
<form action="" class ="form-horizontal" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input class ="form-control" type="submit" value="Сохранить">
</form>
<button class="btn btn-round form-control last">
<a class="btn btn-success" href ="{% url 'admin:users' %}">
К списку пользователей
</a>
</button>
</div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block title %}
    {{title}}
{% endblock %}

{% block content %}
    <div class="users_list">
        <a class="btn btn-primary" href="{% url 'admin:user_create' %}" style="margin: 20px">
            Новый пользователь
        </a>
        <div style="display: flex; flex-wrap: wrap">
            {% for object in object_list %}
                <div class="card" style="margin: 20px">

                    <img src="/media/{{ object.avatar|default:'users_avatars/default.svg' }}" alt="{{ object.username }}" width="150" height="150">
                    <div class="card-body">
                        <div class="user_role">
                            {% if object.is_superuser %}
                                Админитратор
                            {% else %}
                                Пользователь
                            {% endif %}
                            <a  class="btn btn-primary" href="{% url 'admin:user_update' object.pk %}">
                                Редактировать
                            </a>
                            <a class="btn btn-primary" href="{% url 'admin:user_delete' object.pk %} ">
                                Удалить
                            </a>
                        </div>
                        <div class="card-title">
                            <p><strong>{{ object.username }}</strong></p>
                            <p>
                                {% if object.first_name %}
                                    <b>{{ object.first_name|title }}</b>
                                    {% if object.last_name %}
                                        <b>{{ object.last_name|title }}</b>
                                    {% endif %}
                                {% endif %}
                            </p>
                        </div>
                        <div class="user_email">
                            Email: {{ object.email }}
                        </div>
                        <div class="user_lastlogin">
                            Logged: {{ object.last_login }}
                        </div>
                        {% if object.is_active == False %}
                            <div class="user_is_active">
                                <b style="color: red">Не активен</b>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}