adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('books/read/category/<int:pk>/', adminapp.books, name='books'),
    path('books/create/category/<int:pk>/', adminapp.book_create, name='book_create'),
    path('books/read/<int:pk>/', adminapp.BookDetailView.as_view(), name='book_read'),
    path('books/update/<int:pk>/', adminapp.book_update, name='book_update'),
    path('books/delete/<int:pk>/', adminapp.book_delete, name='book_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket_view, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('remove/', basketapp.basket_remove_all, name='remove_all'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

bookshop/urls.py
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('contact/', mainapp.contact, name='contact'),
    path('catalog/', include('mainapp.urls', namespace='catalog')),
    path('shares/', mainapp.shares, name='shares'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.catalog, name='index'),
    path('category/<int:pk>/', mainapp.catalog, name='category'),
    path('book/<int:pk>/', mainapp.book_page, name='book'),
    path('category/<int:pk>/page/<int:page>/', mainapp.catalog, name='page')
]

mainapp/models.py
from django.db import models


class BookCategory(models.Model):
    name = models.CharField(verbose_name='категория', max_length=32)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return '{}'.format(self.name)


class Book(models.Model):
    category = models.ForeignKey(BookCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='название', max_length=64, unique=True)
    address = models.CharField(verbose_name='адрес', max_length=32)
    author = models.CharField(verbose_name='автор', max_length=32, blank=True)
    publishing = models.CharField(verbose_name='издательство', max_length=32, blank=True)
    papers = models.CharField(verbose_name='количество и тип страниц', max_length=32, blank=True)
    mass = models.IntegerField(verbose_name='масса', default=0)
    size = models.CharField(verbose_name='размер', max_length=32, blank=True)
    disc = models.TextField(verbose_name='кратко', blank=True)
    extra_disc = models.TextField(verbose_name='подробно', blank=True)
    price = models.IntegerField(verbose_name='цена', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category.name)

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegistrationForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class ShopUserContactForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    theme = forms.CharField(max_length=100)
    data = forms.CharField(widget=forms.Textarea)

mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, get_object_or_404
from .models import Book, BookCategory
from basketapp.models import Basket
from authapp.forms import ShopUserContactForm
from django.urls import reverse
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
from logger.logger_config import log


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_bestseller():
    books = Book.objects.filter(is_active=True, category__is_active=True)

    return random.sample(list(books), 1)[0]


def get_same_books(bestseller):
    same_books = Book.objects.filter(category=bestseller.category, is_active=True, category__is_active=True).exclude(pk=bestseller.pk)[:4]

    return same_books


@log('Main page is active')
def main(request):
    bestseller = get_bestseller()
    same_books = get_same_books(bestseller)
    new_books = Book.objects.filter(is_active=True, category__is_active=True)[14:20]
    basket = get_basket(user=request.user)
    content = {'basket': basket, 'new_books': new_books, 'bestseller': bestseller, 'same_books': same_books}
    return render(request, 'mainapp/index.html', content)


@log('Basket is active')
@login_required
def basket_view(request):
    basket = get_basket(user=request.user)
    basket_items = basket.order_by('book__category')
    content = {'basket': basket, 'basket_items': basket_items}
    return render(request, 'mainapp/basket.html', content)


@log('Catalog is active')
def catalog(request, pk=None, page=1):
    print(pk)
    links_menu = BookCategory.objects.filter(is_active=True)
    book_list = Book.objects.filter(is_active=True, category__is_active=True)
    new_books = Book.objects.filter(is_active=True, category__is_active=True)[14:20]

    paginator = Paginator(book_list, 10)
    try:
        books_paginator = paginator.page(page)
    except PageNotAnInteger:
        books_paginator = paginator.page(1)
    except EmptyPage:
        books_paginator = paginator.page(paginator.num_pages)

    basket = get_basket(user=request.user)

    if pk:
        if pk == '0':
            category = {'name': 'Все жанры'}
            book_list = Book.objects.filter(is_active=True, category__is_active=True)
        else:
            category = get_object_or_404(BookCategory, pk=pk, is_active=True)
            category_len = Book.objects.filter(category=category)
            book_list = Book.objects.filter(category__pk=pk, is_active=True, category__is_active=True)
        paginator = Paginator(book_list, 10)
        try:
            books_paginator = paginator.page(page)
        except PageNotAnInteger:
            books_paginator = paginator.page(1)
        except EmptyPage:
            books_paginator = paginator.page(paginator.num_pages)
        content = {
            'links_menu': links_menu,
            'book_list': books_paginator,
            'category': category,
            'category_len': category_len,
            'basket': basket,
            'new_books': new_books,
        }
        return render(request, 'mainapp/catalog.html', content)

    content = {
        'links_menu': links_menu,
        'book_list': books_paginator,
        'basket': basket,
        'new_books': new_books,
    }
    return render(request, 'mainapp/catalog.html', content)


@log('Book page is active')
def book_page(request, pk):
    book = get_object_or_404(Book, pk=pk, is_active=True, category__is_active=True)
    same_books = Book.objects.filter(category__pk=book.category.pk, is_active=True, category__is_active=True).exclude(pk=book.pk)[:6]

    basket = get_basket(user=request.user)

    content = {
        'links_menu': BookCategory.objects.all(),
        'book': book,
        'same_books': same_books,
        'basket': basket
    }

    return render(request, 'mainapp/book.html', content)


@log('Contact page is active')
def contact(request):
    basket = get_basket(user=request.user)

    if request.method == 'POST':
        contact_form = ShopUserContactForm(request.POST)
        username = request.POST['username']
        email = request.POST['email']
        theme = request.POST['theme']
        data = request.POST['data']
        if username and email and theme and data:
            try:
                send_mail('{} : {}'.format(username, theme), data, email, ['toscha.nv@gmail.com'], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect(reverse('contact'))
    else:
        contact_form = ShopUserContactForm()
    content = {'contact_form': contact_form, 'basket': basket}
    return render(request, 'mainapp/contact.html', content)


@log('Shares page is active')
def shares(request):
    bestseller1 = get_bestseller()
    bestseller2 = get_bestseller()
    same_books1 = get_same_books(bestseller1)
    same_books2 = get_same_books(bestseller2)
    basket = get_basket(user=request.user)
    content = {
        'basket': basket,
        'bestseller1': bestseller1,
        'bestseller2': bestseller2,
        'same_books1': same_books1,
        'same_books2': same_books2
    }
    return render(request, 'mainapp/shares.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block title %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
    <div class="wrapper">
        <div class="content">
            <header>
                <a href="/" title="На главную">
                    <h1>Bookworm</h1>
                </a>
                <div class="search">
                    <input type="search" placeholder="Поиск">
                    <a href="#">
                        <div class="button">
                            <p>Искать</p>
                        </div>
                    </a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'auth:edit' %}">
                        <div class="button">
                            <p>{{ user.first_name|default:'Пользователь' }}</p>
                        </div>
                    </a>
                    {% endif %}
                    {% if user.is_superuser %}
                    <a href="{% url 'admin:users' %}">
                        <div class="button">
                            <p>Админка</p>
                        </div>
                    </a>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">
                        <div class="button">
                            <p>Выйти</p>
                        </div>
                    </a>
                    {% else %}
                    <a href="{% url 'auth:login' %}">
                        <div class="button">
                            <p>Войти</p>
                        </div>
                    </a>
                    {% endif %}
                </div>
                <!-- Меню сайта -->
                {% block main-menu %}
                {% endblock %}
            </header>
            <hr>
            {% block content %}
            {% endblock %}
        </div>
        <!-- Копирайт -->
        <div class="footer">
            {% block footer-menu %}
            {% endblock %}
            <footer>Все права защищены &copy;2018</footer>
        </div>
    </div>
</body>
</html>

mainapp/templates/mainapp/basket.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block title %}
<title>Корзина</title>
{% endblock %}
{% block js %}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/basket_scripts.js' %}"></script>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}

<!-- Содержимое корзины -->
<div class="basket_list">
{% include 'basketapp/includes/inc_basket_list.html' %}
</div>

{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}

mainapp/templates/mainapp/book.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block title %}
<title>{{book.name}}</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}
<ul class="breadcrumps">

    <li><a href="{% url 'catalog:category' book.category.pk %}">{{book.category.name}}</a></li>
    <li>></li>
    <li><a href="{% url 'catalog:book' book.pk %}">{{book.name}}</a></li>

</ul>

<h2>{{book.author}}: {{book.name}}</h2>

<div class="book-info">

    <a class="book-img" href="{% static book.address %}" target="_blank"><img src="{% static book.address %}" width="185" height="272" title="{{book.name}}"></a>

    <!-- Блоки с контентом -->

    <div class="char-all">

        <div class="char">

            <h3 class="caption">Характеристики товара</h3>

            <ol>
                <li>Автор: {{book.author}}</li>
                <li>Издательство: {{book.publishing}}</li>
                <li>Количество страниц: {{book.papers}}</li>
            </ol>

        </div>

        <div class="char-extra">

            <table>

                <tr>
                    <th colspan="2">Дополнительные характеристики</th>
                    <td></td>
                </tr>
                <tr>
                    <td>ID товара</td>
                    <td>{{book.pk}}</td>
                </tr>
                <tr>
                    <td>Масса</td>
                    <td>{{book.mass}} г</td>
                </tr>
                <tr>
                    <td>Размеры</td>
                    <td>{{book.size}} мм</td>
                </tr>

            </table>

            <p class="price">Цена: {{book.price}} руб.</p>

            <!-- Кнопка покупки -->

            <a href="{% url 'basket:add' book.pk %}">
                <div class="button">

                    <p>Добавить в корзину</p>
                    <div class="basket"></div>

                </div>
            </a>

        </div>

    </div>

    <div class="disc-all">

        <div class="disc">

            <h3 class="caption">Описание товара</h3>

            <p>{{book.disc}}</p>

        </div>
        
        {% if book.extra_disc %}
        <div class="disc-extra">

            <h4 class="caption">Подробное описание товара</h4>

            <div class="disc-extra-text">

                <p>{{book.extra_disc}}</p>

            </div>

        </div>
        {% endif %}

    </div>

</div>

<!-- Ссылки на другие книги -->

<div class="related">

    <div class="related-h">
        <h3>Похожие товары</h3>
        <a class="book-link" href="{% url 'catalog:category' book.category.pk %}">
            <h4>Посмотреть все</h4>
        </a>
    </div>

    <div class="related-book">
        {% for book in same_books %}
        {% include 'mainapp/includes/inc_related_book.html' %}
        {% endfor %}
    </div>

</div>
{% endblock %}

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block title %}
<title>Каталог</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}

<div class="paginator">
    {% if book_list.has_previous %}
        <a href="{% url 'catalog:page' category.pk book_list.previous_page_number %}">
            <
        </a>
    {% endif %}
    <span class="current">страница {{ book_list.number }} из {{ book_list.paginator.num_pages }}</span>
    {% if book_list.has_next %}
        <a href="{% url 'catalog:page' category.pk book_list.next_page_number %}">
            >
        </a>
    {% endif %}
</div>

<!-- Имеющиеся товары -->

<div class="book-all-1">
    
    {% include 'mainapp/includes/inc_categories_menu.html' %}

    <div class="book-all-2">
        
        {% for book in book_list %}
            <div class="book">
            
                <img src="{% static book.address %}" width="92.5" height="136">
                <a class="book-link" href="{% url 'catalog:book' book.pk %}">{{book.name}}</a>
                <p class="price">{{book.price}} р.</p>
                <a class="buy-link" href="{% url 'basket:add' book.pk %}">В корзину</a>

            </div>
        {% endfor %}

    </div>

</div>

<div class="related">

    <div class="related-h">
        <h3>Новые товары</h3>
        <a class="book-link" href="#">
            <h4>Посмотреть все</h4>
        </a>
    </div>

    <div class="related-book">
        {% for book in new_books %}
        {% include 'mainapp/includes/inc_related_book.html' %}
        {% endfor %}
    </div>

</div>
{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% block title %}
<title>Контакты</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}

<div class="contact-box">

    <div class="report">

        <h2>Напишите нам</h2>

        <!-- Форма для связи с магазином -->

        <form action="{% url 'contact' %}">

            <fieldset>
                <label for="id_username">Имя:</label>{{ contact_form.username }}
                <label for="id_email">E-mail:</label>{{ contact_form.email }}
                <label for="id_theme">Тема:</label>{{ contact_form.theme }}<br>
                {{ contact_form.data }}<br>
                <input type="reset" value="Очистить">
                <input type="submit" value="Отправить">

            </fieldset>

        </form>

    </div>

    <!-- Информация о магазине -->

    <div class="adress">

        <h2>Адрес</h2>

        <ul>

            <li>Номер телефона: +7(999)999-99-99</li>
            <li>Адрес: г. Калининград ул. Первомайская 54а</li>
            <li>E-mail: feedback@bookworm.com</li>

        </ul>

    </div>
</div>

<!-- Карта -->

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d147513.06792274333!2d20.324447259571603!3d54.71152875056549!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46e33d8d4b7c21a9%3A0x5050960016126ed3!2sKaliningrad%2C+Kaliningrad+Oblast!5e0!3m2!1sen!2sru!4v1521393046617" allowfullscreen></iframe>
{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block title %}
<title>Bookworm</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}
<!-- Приветственное сообщение -->

<div class="message">

    <p>Добро пожаловать в книжный интернет-магазин Bookworm! Огромное количество книг различных жанров, еженедельные акции и постоянные скидки на продукцию ждут Вас. Ознакомьтесь с ассортименотом во вкладке "Каталог", свяжитесь с нами в любое время во вкладке "Контакты" и не пропустите горячие предложения во вкладке "Акции".</p>

</div>

<!-- Бестселлеры -->

<h2>Бестселлеры</h2>

<div class="best">

    <div class="best1">

        <div class="best1-1">

            <h3>{{bestseller.author}}: {{bestseller.name}}</h3>
            <p>{{bestseller.disc}}</p>

            <a href="{% url 'basket:add' bestseller.pk %}">
                <div class="button">

                    <p>Добавить в корзину</p>
                    <div class="basket"></div>

                </div>
            </a>

            <a class="book-link" href="{% url 'catalog:book' bestseller.pk %}">Подробнее ></a>

        </div>

        <img src="{% static bestseller.address %}" width="185" height="272">

    </div>

    <div class="best2">
            {% for book in same_books %}
            <a href="{% url 'catalog:book' book.pk %}"><img src="{% static book.address %}" width="138.75" height="204"></a>
            {% endfor %}
    </div>

</div>

<!-- Новые книги -->

<div class="related">

    <div class="related-h">
        <h3>Новые товары</h3>
        <a class="book-link" href="#">
            <h4>Посмотреть все</h4>
        </a>
    </div>

    <div class="related-book">
        {% for book in new_books %}
        {% include 'mainapp/includes/inc_related_book.html' %}
        {% endfor %}
    </div>

</div>
{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}

mainapp/templates/mainapp/shares.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block title %}
<title>Акции</title>
{% endblock %}
{% block main-menu %}
{% include 'mainapp/includes/inc_main_menu.html' %}
{% endblock %}
{% block content %}

<!-- Активные акции -->

<div class="message">

</div>

<div class="best">

    <div class="best1">

        <div class="best1-1">

            <h3>{{bestseller1.author}}: {{bestseller1.name}}</h3>
            <p>{{bestseller1.disc}}</p>

            <a href="{% url 'basket:add' bestseller1.pk %}">
                <div class="button">

                    <p>Добавить в корзину</p>
                    <div class="basket"></div>

                </div>
            </a>

            <a class="book-link" href="{% url 'catalog:book' bestseller1.pk %}">Подробнее ></a>

        </div>

        <img src="{% static bestseller1.address %}" width="185" height="272">

    </div>

</div>

<div class="shares">

        {% for book in same_books1 %}
        {% include 'mainapp/includes/inc_related_book.html' %}
        {% endfor %}

<!--
        {% for book in same_books2 %}
        {% include 'mainapp/includes/inc_related_book.html' %}
        {% endfor %}
-->

</div>

<!--
<div class="best">

    <div class="best1">

        <img src="{% static bestseller2.address %}" width="185" height="272">

        <div class="best1-1">

            <h3>{{bestseller2.author}}: {{bestseller2.name}}</h3>
            <p>{{bestseller2.disc}}</p>

            <a href="{% url 'basket:add' bestseller2.pk %}">
                <div class="button">

                    <p>Добавить в корзину</p>
                    <div class="basket"></div>

                </div>
            </a>

            <a class="book-link" href="{% url 'catalog:book' bestseller2.pk %}">Подробнее ></a>

        </div>

    </div>

</div>
-->
{% endblock %}
{% block footer-menu %}
{% include 'mainapp/includes/inc_footer_menu.html' %}
{% endblock %}